// <auto-generated />
namespace Covid19Tracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class jason21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jason21));
        
        string IMigrationMetadata.Id
        {
            get { return "202011232250264_jason21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
